### ISSUE TITLE
USER STORY: Publish poll

### ISSUE THREAD

**Issue by barryCFlynn** [barryCFlynn/Agile-Training#4]
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll

## Acceptance Criteria

- the poll should disappear at 11:59 pm on the target date
- the real estate of the "Poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other poll is active 
- the administrator expiry date should be at least 3 days after the current date.
  
## Tasks

- [ ] update the admin module view: the pool design (HTML and CSS ) to include date picker
- [ ] update the website view: show "Stay Tuned, a new poll is coming soon"
- [ ] create JavaScript function to validate the expiry date is at least after 3 days.
- [ ] create a job to check expired polls everyday at 11:59 pm and hide them
- [ ] update the controller function
- [ ] update unit test scripts
- [ ] test the functionality
